### PR TITLE
Smaller images

### PR DESCRIPTION
**Pull request by kornelski**
I've given images [ImageOptim](http://imageoptim.com) treatment. `client/img` is 42% smaller.

### CODE REVIEW

**Comment by arcanis** [comment]
42, eh ?

**Comment by mathiasbynens** [comment]
Classic @pornel.

**Comment by kornelski** [comment]
@arcanis Yes, I've optimized the universe and everything.

**Comment by kornelski** [comment]
25 days to merge it? Hello? Is anybody here?

**Comment by justinclift** [comment]
Good work @pornel.  Committed this to the dev repo [here](https://github.com/browserquest/BrowserQuest).

Trying to get everything caught up and in shape for future dev work.

Any chance you want to help? (looking for committers) :D

**Comment by kornelski** [comment]
Well, that took a while… 

I could help if you need any optimisations :)

**Comment by justinclift** [comment]
Excellent, will ping you as/when new image assets are created, so they can be optimised. :)

**Pull request closed without merging**
