### PR TITLE
Update front page link

### PR DESCRIPTION
**Pull request by lotus647**
Added 'The' before 'code' in README.md, so that it will allow me to fork. I didn't change any code, just changed the link on the front page to be up-to-date.

### CODE REVIEW

**Comment by 8thcoder** [comment]
Bruh was it necessary to add "The" for it to allow you to fork?

**Comment by lotus647** [comment]
yes

**Comment by lotus647** [comment]
bro why does no one allow me to merge AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH

**Comment by lotus647** [comment]
Pull requests aren't accepted here.

This mozilla/BrowserQuest repository is kept frozen to the original release of source code by Little Workshop.

But don't despair, all is not lost! :)

Please take a look at the Community Forks page:

    https://github.com/mozilla/BrowserQuest/wiki/Community-Forks

This lists the various groups developing BrowserQuest, each with their own vision and goals for the project.

If you want to join in BrowserQuest development, these groups are friendly, and will warmly welcome your assistance. :)

Alternatively, you can start your own group then add a link to it here... :)

Other documentation
A quick start installation guide using Amazon EC2 hosting can be found here: https://github.com/mozilla/BrowserQuest/wiki/Quick-Start-using-Amazon-EC2

**Comment by lotus647** [comment]
bruh

**Pull request closed without merging**
