### PR TITLE
Added radix of 10 to calls to parseInt

### PR DESCRIPTION
**Pull request by rob-mccann**
In line with the recommendation here https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/parseInt

_NOTE_ I am, of course, assuming the input string to these is decimal rather than hex or any other type.

### CODE REVIEW

**Comment by hashar** [comment]
Sounds good. JavaScript linter you will use :-D

**Comment by justinclift** [comment]
Tried this out with this [new dev repo](https://github.com/browserquest/BrowserQuest), but it causes this error to occur when clients connect:

```
[Fri Sep 14 2012 04:11:58 GMT+1000 (EST)] ERROR uncaughtException: TypeError: Object #<Object> has no method 'hp'
```

Any ideas?

**Comment by englercj** [comment]
@justinclift I think that may have to do with what seems to be an error in his commit:

``` javascript
-if(!(typeof exports === 'undefined')) {
+if((typeof exports === 'undefined')) {
```

Try adding this pull request, but ignoring the changes to `server/js/formulas.js`

**Comment by justinclift** [comment]
Ahh cool.  Thank @englercj, that lets it work.

Just committed this pull request to the dev repo [here](https://github.com/browserquest/BrowserQuest).

Trying to get everything merged into one spot that gets attention, so future development is easier. :)

**Comment by nickdesaulniers** [comment]
Thanks for taking a look at the source code for BrowserQuest!  BrowserQuest was developed by [Little Workshop](http://www.littleworkshop.fr/) on behalf of Mozilla to showcase how the Web is the ultimate cross platform for games.

Mozilla does not currently have the resources to maintain BrowserQuest, but you should check out some of these amazing community forks instead!  Feel free to add your fork to the [wiki](https://github.com/mozilla/BrowserQuest/wiki/Community-Forks).

**English**
- [browserquest/browserquest](https://github.com/browserquest/BrowserQuest) - The general development group
  - Running game here, you're welcome to join: http://browserquest-teambq.rhcloud.com:8000
- [ParticleQuest](https://github.com/particlequest/ParticleQuest) - Making particle physics fun. The goal of this project is to create a science based story modifying BrowserQuest.

**Korean**
- Burger Burger Online: http://burgerburger.kr - Extremely well developed, significantly expanded from the original BrowserQuest
  - Community: http://asky.freethinker.kr
  - English is being added
  - Older source: https://github.com/browserquest/BrowserQuest-Asky

**Android**
- [BrowserQuest for Android](https://svn.strasweb.fr/listing.php?repname=Pierre+Rudloff&path=%2Fbrowserquest%2F) - BrowserQuest client, [available in the Android store](https://play.google.com/store/apps/details?id=fr.strasweb.browserquest)

**Windows Phone**
- [BrowserQuest for Windows Phone](http://www.windowsphone.com/en-US/store/app/browserquest/9df4ba1e-fa73-40d1-b391-4773d287db35) - BrowserQuest, in Windows Phone store

**Erlang based**
- [sedrik/bqs](https://github.com/sedrik/bqs) - Erlang implementation of the BrowserQuest server

**C++ based**
- [chain710/browserquestcc](https://github.com/chain710/browserquestcc) - C++ implementation of the BrowserQuest server

## Related
- [HabitRPG](https://habitrpg.com/static/front) - A habit building program which treats your life like a Role Playing Game
  - Uses the BrowserQuest character icons (CC-licensed) for some of their stuff, and is looking to contribute back the icons they've developed since

## No longer actively developed

**French**
- UFB World: http://ufbteam.com/fr
  - Source: https://github.com/hackziner/ufbworld

**Pull request closed without merging**
