### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thingdiputra**
add nodejs's link, so it will easier for people to install nodejs.

### CODE REVIEW

**Comment by HavoStrean** [comment]
d野鹅#如t

**Review by ghost — APPROVED** [review]
This seems like a pretty good idea.

**Review by JPLovelace — APPROVED** [review]

**Comment by rekcah1986** [comment]
Good job~

**Comment by baco25** [comment]
Nice

**Comment by MaxGamerProPlayer** [comment]
👍😀

**Review by artkirienko — APPROVED** [review]

**Review by MaxGamerProPlayer — APPROVED** [review]

**Comment by davidoff00008** [comment]
Gut

**Pull request closed without merging**
