### PR TITLE
SocketIO Implementation

### PR DESCRIPTION
**Pull request by nenuadrian**
This is due to the deprecated and obsolete libraries.

I haven't tested the game fully, but I've followed your code structured and also updated RequireJS and implemented SocketIO based on your classes to keep every single functionality in place.

Seems to be working quite well and Thank you for sharing this project with us!

Most certainly the best open source 2d multiplayer game out there!

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
Thank you for taking the time to assemble this PR.  Unfortunately, we have frozen development of this fork as a reference.  Please see: https://github.com/mozilla/BrowserQuest/wiki#important-notice

**Comment by nenuadrian** [comment]
Hey Nick,

Thanks for letting me know. I can't really figure out how to edit the wiki. Any way my project can get added to it?

There's a demo usually running at http://browserquest.codevolution.com

Thanks again!

**Comment by max107** [comment]
@nenuadrian :+1: thanks!

**Comment by nickdesaulniers** [comment]
On the [page of community forks](https://github.com/mozilla/BrowserQuest/wiki/Community-Forks) there should be an edit button on the top right, next to the green New Page button.  I'll triple check this repo is set up for anyone to edit the wiki.

**Comment by nickdesaulniers** [comment]
Indeed:

```
GitHub Wikis is a simple way to let others contribute content. Any GitHub user can create and edit pages to use for documentation, examples, support, or anything you wish. 
```

is checked.

**Comment by nenuadrian** [comment]
screen shot 2015-08-04 at 19 35 19

I know where it should be, but is it there? Maybe you locked the project? Or I have to pull the wiki and push the wiki?

**Comment by nickdesaulniers** [comment]
What is going on here?
screen shot 2015-08-04 at 1 08 39 pm
Maybe @justinclift knows? Otherwise, I'll contact GH directly about this.  We have edits from non repo contributors on the wiki...

**Comment by justinclift** [comment]
Hmmmm, from memory I saw the same read-only behaviour on this wiki a while ago when I wanted to update it.

@nickdesaulniers If you have admin access for the main project settings, maybe look in the "Features" area and see if the "Restrict editing to users in teams with push access only" option is turned on:

&nbsp; &nbsp; https://github.com/mozilla/BrowserQuest//settings

Kind of guessing that might be the problem. :wink:

**Comment by nickdesaulniers** [comment]
right on! try again now?

**Comment by justinclift** [comment]
The Edit button is showing up for me now. :smile:

**Comment by nenuadrian** [comment]
Yeah, no it's perfect now! Thank you, edited already.

**Pull request closed without merging**
