### PR TITLE
Cleaning up build.sh

### PR DESCRIPTION
**Pull request by bahamas10**
- Quoting all variables to avoid possible word splitting
- Sanity checking chdir(2) calls

### CODE REVIEW

**Comment by awbush** [comment]
Someone please merge this, it fixes build failures when there are spaces in the path, e.g. `~/Some Directory/BrowserQuest/bin`.

(I'll note that I only had to quote `$CURDIR` twice, but the rest of the changes here look good too.)

**Comment by bahamas10** [comment]
I didn't want to step on the toes of pull request 32, I thought those changes were a part of https://github.com/mozilla/BrowserQuest/pull/32, but I realized I had just read your comments.

**Comment by bahamas10** [comment]
Technically there is nothing in this script that is bash specific (parameter expansion, etc) so it could just be invoked with sh.

**Comment by justinclift** [comment]
@bahamas10 Just manually merged this pull request to the dev repo [here](https://github.com/browserquest/BrowserQuest).

However, pull request 32 had been applied prior, so it wasn't a clean apply.  Had to muck around with it a bit.

If you could take a look, just to make sure it's as you intended, that would be cool. :)

That being said, it did work fine for me when testing a path against a repo path using spaces.

**Comment by bahamas10** [comment]
Fantastic, thanks @justinclift, it looks good to me!

**Pull request closed without merging**
