### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by 7rin0**
Fix installation issues.
(tested on Ubuntu 15.10, node v5.8.0, npm 3.8.3)

### CODE REVIEW

**Comment by guiferpa** [comment]
You updated package.json file because the module `websocket-server` is unpublished? Case yes, you forgot edit the yours imports/requires :smiley:

**Comment by guiferpa** [comment]
I wanted much running this project :8ball:

**Comment by justinclift** [comment]
Oops, sorry @7rin0.  Just saw this.  It's probably worth reading over this:

&nbsp; &nbsp; https://github.com/mozilla/BrowserQuest/wiki

BrowserQuest is kind of a dead project.  There were some active forks for a while (as in the above wiki link), but nothing much seems to be happening any more. 😦

**Comment by kirkins** [comment]
@justinclift so you can't pull a PR that fixes a broken package just because Mozilla isn't funding further development?

09-roll-safe w710 h473

Typical Mozilla. Silly company, outsting the genius behind it, now you're about to be run out of the valley.

photo_2018-05-05_14-37-53

**Comment by justinclift** [comment]
Well, with this specific project the Mozilla leadership didn't seem to realise what a big hit/impact kind of thing this would be when it was released.  From rough memory (may not be totally 100% spot on), the project went through a long period of development hell or similar before it actually got out the door.

So, when the project was finally released there wasn't any expectation of building a Community around it.  "Glad to see the end of it" is the feeling I got from some of the emails forwarded to me (much later on). :wink:

It was just a code drop and nothing else.  They literally weren't prepared for any uptake, and - from my point of view - ignored all attempts to contact them to enable the building of a Community.

Eventually some of us got in touch with various Mozilla people, which helped, but they weren't willing to give anyone write access to the repo. It's under the "mozilla" namespace here on GitHub, so they didn't want to have any liability in case someone did something stupid in the repo.

No attempts to present ways around that met any success.  They did suggest we continue development  in a fork (browserquest/browserquest or whatever), without really understanding that's effectively also saying "No".

In hindsight, what could have been done better?

1. *Move* this main repo under some other non-Mozilla brand name org.  browserquest/browserquest would have been a good choice for that, instead of as a fork, but too late now. :wink:

2. Give Admin access to some group of people so PR's and similar could be merged.  eg allow the building of a Community

Hmmm, those are the two foundation ones I think.  There might have been more useful adjustments afterwards, but those two were the biggies I recall. :smile:

**Pull request closed without merging**
