### PR TITLE
Some minor quibbles

### PR DESCRIPTION
**Pull request by willurd**
Came across some small stuff while I was looking over the code. Hopefully I can contribute something more exciting in the future.

Also, apologies if I'm way off base here. I only updated things I thought were mistakes.

### CODE REVIEW

**Comment by trevnorris** [comment]
Wow, hard core to find all those little things.

**Comment by willurd** [comment]
Sometimes I find it therapeutic :) I also find it a good way to get familiar with a code base. Wouldn't want to do it all the time though.

**Comment by Xarias09** [comment]
Maybe PVP/levels ? ;)

**Comment by justinclift** [comment]
@willurd Just committed your pull request to the repo [here](https://github.com/browserquest/BrowserQuest).

Trying to get all of the useful looking commits together in one spot, to make future development easier. :)

**Comment by willurd** [comment]
@justinclift Sweet thanks!

**Pull request closed without merging**
